name: Django CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    if: github.actor != 'github-actions[bot]' && github.actor != 'dependabot[bot]'

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12] # since your project requires >=3.12

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install Dependencies
      run: |
        cd server && uv sync

    - name: Create .env for CI
      working-directory: server
      run: |
        cat <<EOF > .env
        SECRET_KEY=${{ secrets.SECRET_KEY }}
        DEBUG=True
        SUPABASE_URL=${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
        PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}
        OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
        POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
        POSTGRES_DB=${{ secrets.POSTGRES_DB }}
        POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        EOF
        
    - name: Run Tests
      working-directory: server/app
      run: |
        uv run python manage.py test
